plugins:
  mentionables_enabled:
    default: true
    client: true
  mentionables_source:
    type: enum
    default: 'google_sheets'
    choices:
      - google_sheets
  mentionables_onebox_fallback: false
  mentionables_generate_slugs: true
  mentionables_autocomplete_limit:
    default: 5
    client: true
  mentionables_google_spreadsheet_id: ''
  mentionables_google_worksheet_names:
    type: list
    default: 'Sheet1'
  mentionables_google_worksheet_max_row:
    default: 300
  mentionables_google_service_account_private_key: ''
  mentionables_google_service_account_email: ''
  mentionables_composer_button_icon: 
    default: 'plus'
    client: true
